### ISSUE TITLE
EASDG

### ISSUE THREAD

**Issue by bartvm** [mila-udem/platoon#1]
@abergeron @lamblin @nouiz @mgermain 

The distributed algorithm I would like to try and implement is EASGD ([arXiv:1412.6651](http://arxiv.org/abs/1412.6651)), which is beautifully simple (see algorithm 1 in the paper):

```python
x = params.get_value()
# x_tilde are the memory-mapped shared parameters
diff = alpha * (x - x_tilde)
params.set_value(x - diff)
x[...] = x + diff
```
In general, distributed algorithms can probabably take the form `update_params(shared_params, worker_params)`, which is a function that is expected to update both in place, so:
```python
easdg(x_tilde, x):
    diff = alpha * (x - x_tilde)
    x_tilde[...] = x - diff
    x[...] = x + diff
x = params.get_value()
easdg(x, x_tilde)
params.set_value(x)
```

**Comment by carriepl** [comment]
Closing the issue as this has been implemented.
