### ISSUE TITLE
Valid command do not valid with master weights and cause expired local weights

### ISSUE THREAD

**Issue by nouiz** [mila-udem/platoon#15]
- If a worker receive a valid command, he will do validation with the current local weights. I would expect him to do so with the master weights.
- After the valid command, is the worker receive a train or another valid command, he will continue to use a old "expired" local weights. If this is bad or not isn't clear. I think it is bad, other people aren't as sure. We should test it or at least provide a way to let people test both options.

**Comment by abergeron** [comment]
This is not a bug in platoon but in the LSTM example that I made.  It's entirely possible to do something different.
