### ISSUE TITLE
python lstm.py always needs a mode argument

### ISSUE THREAD

**Issue by rizar** [mila-udem/platoon#17]
https://github.com/mila-udem/platoon/blob/master/example/readme.txt says that after I ran the first lstm.py as `lstm.py init`, I should run other workers. I does not say with which mode, and from the code it seems even `lstm.py abacaba` works.

I can make a PR that would make `mode` handling more consistent.

**Comment by abergeron** [comment]
Sure if you want to do it.  I made it as experimental code so there are some rough edges.

**Comment by mgermain** [comment]
This should be addressed by #19 .

**Comment by mgermain** [comment]
PR #29 fixed this.
