### ISSUE TITLE
LSTM example : copy params locally before entering main loop

### ISSUE THREAD

**Issue by carriepl** [mila-udem/platoon#33]
Currently, the model gets the latest parameters *and then* compiles the theano function and enters the main loop. If the compilation takes too long, by the time it starts training, the parameters will be outdated.

It applies a bit less to the LSTM example since its compilation time is very reasonnable but since many people will simply copy paste from the example, it would be a good thing for this example to copy the params locally just before entering the main loop. (some students faces that issue when trying to adapt the lstm example to their huge models which can take >30 minutes to compile)

**Comment by mgermain** [comment]
I'm not sure that's a problem for 2 reasons:
- Even if the model takes an hour to compile, they all do in parallel so they should start around the same time anyway. (Assuming you started the workers at the same time or used the launcher)
- Shouldn't the "elastic" nature of the algorithm take care of that a bit ? Also we sync befor testing, so the weight will be updated there anyway.

All that said, if you think it's a good idea to add a sync anyway I really don't mind.

**Comment by carriepl** [comment]
* They won't necessarily start at the same time. The compile locks means there could be large differences between the start time of various workers, even if they were started at the same time.
* Also, there is no guarantee the workers will be started at the same time.  What if I start my job and then get access to another GPU and want to add a new worker to my ongoing job? What if one of my workers was killed but I want to restart it?
* The elastic nature of the algorithm is part of the issue. Yes, it means the worker's params will gradually catch up but the point is that as long as they are still catching up, those outdated params have the potential to stall or even derail training. And the more outdated they are, the greater the effect.
* Depending on the size of the dataset, there can be quite a few updates before any one worker gets to the point where it validates so we cannot really count on that.

**Comment by mgermain** [comment]
Good, make sense. I'll make a PR right now.
