### ISSUE TITLE
platoon_launcher vs platoon-launcher

### ISSUE THREAD

**Issue by dwf** [mila-udem/platoon#40]
Can I suggest `platoon-launcher` as the name of the executable (dash rather than underscore)? The underscore is necessary for modules because of the operator. For command-line stuff, the extra shift is annoying to type. This also keeps consistency with `blocks-continue`, `fuel-convert`, etc.

**Comment by mgermain** [comment]
Sure, I have no objection.
Is there a linux/POSIX standard for that?

**Comment by bartvm** [comment]
No, but http://unix.stackexchange.com/a/7371

**Comment by nouiz** [comment]
I don't have a preference, but I agree, as it will be written frequently,
not having to press shift and for consistency, I think it would be good to
change it.

**Comment by mgermain** [comment]
Ok, changing it!
