### ISSUE TITLE
How are the parameters synchronised?

### ISSUE THREAD

**Issue by webeng** [mila-udem/platoon#48]
How are the parameters synchronised?

Are you averaging them or you use another methodology?

Thank you

**Comment by mgermain** [comment]
We use EASGD, there is more details in the README on the main page.
"The framework allows multiple data-parallel algorithms, but only
[EASGD](http://arxiv.org/abs/1412.6651) and ASGD is currently implemented."

The documentation in [param_sync.py](https://github.com/mila-udem/platoon/blob/master/platoon/param_sync.py#L60) line 60 gives more information.

Simply put we, every T updates, we take the difference between the worker params and the master params and update both with a fraction of that difference.

```
diff = w_worker - w_master
w_worker = w_worker - alpha * diff
w_master = w_master + alpha * diff
```
