### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by bartvm** [mila-udem/platoon#53]
The current code isn't compatible with Python 3 at all, which is annoying. I run Python 3 and this causes any project that imports Platoon somewhere to fail immediately.

In general, even if the lab still develops on Python 2, we should at least make sure that the tools don't crash for people who run Python 3. We're going to have to switch someday (sooner rather than later) and legacy Python compatibility is pretty trivial with `six` most of the time.

**Comment by bartvm** [comment]
#54 fixes the `print` statements in the `platoon-launcher` script. For ZMQ we need to either use the `send_string` and `recv_string` methods instead of `send` and `recv`, or explicitly send bytes. We also need to use `memoryview` instead of `buffer` in Python 3 (see `fuel.utils`).

**Comment by dwf** [comment]
Can I add an exasperated "why??!" The largest hurdle, single codebase Theano support, is gone, thanks to myself and @abergeron. Python 3 is better in almost every way, it makes it easier to develop bug free code, and conda makes it trivial to deploy. New projects should not be using legacy Python...

**Comment by bartvm** [comment]
:+1:

**Comment by mgermain** [comment]
You are both right about this, thanks for the reminder and the PR.
