### ISSUE TITLE
The LSTM example runs CPU only

### ISSUE THREAD

**Issue by petrbel** [mila-udem/platoon#59]
I installed Platoon and tried to run the LSTM example on my 4 GPUs (`gpu0`...`gpu3`) Ubuntu server. I followed the example tutorial, hence in the `example/lstm` directory I run (in separate terminals):

- `$ THEANO_FLAGS='device=cpu' python -u lstm_controller.py`
- `$ THEANO_FLAGS='device=gpu2' python -u lstm_worker.py`
- `$ THEANO_FLAGS='device=gpu3' python -u lstm_worker.py`

The result is that the CPU runs up to 100% and GPUs (according to `nvidia-smi`) stay still. I tried to force the device by using:

- `$ THEANO_FLAGS='device=gpu2,force_device=True' python -u lstm_worker.py`
- `$ THEANO_FLAGS='device=gpu3,force_device=True' python -u lstm_worker.py`

But nothing changed. Finally I tried to mask out the first two GPUs in order to make the scripts think they use the first two GPUs:

- `$ CUDA_VISIBLE_DEVICES='2,3' THEANO_FLAGS='device=gpu0,force_device=True' python -u lstm_worker.py`
- `$ CUDA_VISIBLE_DEVICES='2,3' THEANO_FLAGS='device=gpu1,force_device=True' python -u lstm_worker.py`

But it didn't help either.

What's really weird is the Theano debug output stating "Using gpu device 2: Tesla...." even though the computation clearly runs on CPU only.

Am I doing something wrong or is it some kind of bug? Thanks

**Comment by nouiz** [comment]
Try with the Theano flag floatX=float32. By default, float are float64 and
the current GPU back-end only support float32.

We make examples use floatX.

**Comment by petrbel** [comment]
Oh that did the trick. I thought `float32` is default. Thank you for your prompt reply :)
