### ISSUE TITLE
What is the status on controller-handled dataset?

### ISSUE THREAD

**Issue by rparrapy** [mila-udem/platoon#63]
The README file of the Batched Pixel Sum example warns:

> - Using more than 1 worker causes problem at the moment for THIS particular example.
>   
>The reason is that we are using the "dataset handled by the controller" feature which is not quite ready yet.
> 

I assume this refers to using the Controller `send_mb` method (which uses a Zeromq load balancer) to distribute the mini batches among Workers.

What is the status on this feature? I'd like to give Platoon a try and this seems like an important block for a data parallelism framework.

**Comment by mgermain** [comment]
There was no demand to expand this feature so far as it's not mandatory to fully take advantage of Platoon.

Most people let each worker load the dataset individually and make sure they use a different seed to randomize the mini-batches (The controller send which random seed to use).

You still can use the mini-batch server though. The only issues we have with it right now are #23 and #24 and you can walk around them pretty easily.
