### ISSUE TITLE
How to pass different parameters to workers?

### ISSUE THREAD

**Issue by avostryakov** [mila-udem/platoon#65]
I want that every worker trains on its own train data. So, I want to pass a different file name to every worker. How to do it?

**Comment by mgermain** [comment]
The simplest way to do this right now is to start the controller and workers manually in different shells (ie: not using platoon-launcher) and passing the different name to them individually.

Or, each worker can ask the controller with part of the dataset to load and then load the right one.

**Comment by avostryakov** [comment]
Thank you for the answer!

**Comment by mgermain** [comment]
My pleasure.
