### ISSUE TITLE
Reason: context name None not defined

### ISSUE THREAD

**Issue by mingxuan** [mila-udem/platoon#73]
Hi all,

I tried the new version of platoon, and found in 
platoon/channel/worker.py 
"from theano import gpuarray as theanoga" may raise some error.

I fixed this to "from theano.sandbox import gpuarray as theanoga "
and got another warning 
"WARNING! Failed to register in a local GPU comm world.
  Reason: context name None not defined"

I have installed pygpu and nccl.
Could you help me?

**Comment by nouiz** [comment]
You must use the development version of Theano. Not the last release 0.8.2
with the new back-end.

Then the first import will work with that Theano version.

**Comment by mingxuan** [comment]
Problem solved! 
Thank you so much.
