### ISSUE TITLE
LSTM example does not work with synchronous all_reduce interface

### ISSUE THREAD

**Issue by slefrancois** [mila-udem/platoon#78]
The LSTM example fails to finish training with the all_reduce interface. It was made for the asynchronous param_sync interface with workers sending messages asking what to do next and writing to shared memory when told.

With all_reduce, the workers train, and one of them converges and stops, but the other get stuck in its training loop when it tries to calculate f_grad_shared. It might be trying to perform an all_reduce but cannot communicate with workers who have finished.

A suggestion it to rewrite the example from scratch for the synchronous interface. This would involve having workers train together, then wait to validate together, and stop together. Ideally, the validation set would be split between workers.

**Comment by dvector89** [comment]
I also get stuck with this example. My log info is that:

## Mapped name None to device cuda0: Tesla K40m
PCI Bus ID: 0000:0D:00.0
Using cuDNN version 5103 on context None
WARNING! Failed to register in a local GPU comm world.
Reason: Error loading library
WARNING! Platoon `all_reduce` interface will not be functional.
Traceback (most recent call last):
  File "lstm_worker.py", line 662, in <module>
    numpy.random.seed(SEED + worker.global_rank)
  File "~/tools/platoon-master/platoon/channel/worker.py", line 215, in global_rank
    return self._global_rank
AttributeError: 'Worker' object has no attribute '_global_rank'

Is there anyone who can figure it out? Thanks.

**Comment by slefrancois** [comment]
@dvector89 , this sounds like libgpuarray has not been linked to NCCL. You must install NCCL from nvidia's website, then build libgpuarray, cmake should say it found NCCL.

**Comment by dvector89** [comment]
Thanks @slefrancois I'll try it.

**Comment by dvector89** [comment]
@slefrancois I'm failed to install NCCL. I installed it according to https://github.com/NVIDIA/nccl . The error information is below:
[@nk nccl-master]$ make CUDA_HOME=/usr/local/cuda test
Compiling src/libwrap.cu                      > /search/odin/shiliangliang/tools/nccl-master/build/obj/libwrap.o
nvcc fatal   : Value 'gnu++0x' is not defined for option 'std'
make: *** [/search/odin/shiliangliang/tools/nccl-master/build/obj/libwrap.o] Error 1

Could you give me some advice? Thanks.

**Comment by slefrancois** [comment]
That looks like an issue with your local environment, either the compiler configuration or CUDA installation.

I think this is beyond the scope of this issue, if you need further help I recommend you use support channels for NCCL or maybe the theano-users mailing list.

**Comment by nouiz** [comment]
This is for the NCCL channel. But this error remind me that maybe you don't
use a good g++ compiler version.

On Tue, Dec 20, 2016 at 10:02 AM, Simon Lefrancois <notifications@github.com

**Comment by lamblin** [comment]
Closed by #83.
