### ISSUE TITLE
cannot find command 'platoon-launcher'

### ISSUE THREAD

**Issue by xiongxiaochu** [mila-udem/platoon#81]
I just downloaded this framework, but i failed running the example program. I just run it according to the usage:
platoon-launcher <experiment-name> lstm -D gpu0 gpu1, 
but it says "cannot find command platoon-launcher", and when i manually run this program, according to: 
`THEANO_FLAGS='device=cpu' python -u lstm_controller.py`, 
it says 'lstm_controller.py: error: too few arguments'. 
So is there anybody can tell me why?

**Comment by nouiz** [comment]
What error did you got?

**Comment by xiongxiaochu** [comment]
just like the information i described before, the error is:
**cannot find command platoon-launcher**.
and when i manually run the program in the lstm folder, according to: THEANO_FLAGS='device=cpu' python -u lstm_controller.py,
the error is: '**lstm_controller.py: error: too few arguments**'.
