### ISSUE TITLE
Exaggerated time cost when building/ compiling theano functions

### ISSUE THREAD

**Issue by kobecsb** [mila-udem/platoon#88]
I was using the newest version of platoon, and newest version of [theano](https://github.com/Theano/Theano) to build a multi-node [neural machine translation](https://github.com/rsennrich/nematus) system.
I implemented the controller and worker on two different platoon version, platoon.0.5 (around july 2016) and platoon-0.6 (current version), respectively.

But the compiling time for theano functions varies. The compiling time of second version is multiple times of the first one. I didn't record the time accurately, but the time cost difference is remarkable.

I'm wondering why did this happen. I'm not sure whether it's a bug or my wrong implementation for the second version.

#### implementation info to help

1. for the old version. I implemented a controller and a worker. In this version, we should start a controller, then start multiple workers (I'm pretty sure this implementation is correct).
2. for the new version. I implemented a controller and a worker, too. But we only need to set all the parameters first, then start a controller. Then the controller will start workers automatically (I'm not very sure about the correctness of this version)..

**Comment by nouiz** [comment]
Theano generate/compile C code when we compile a Theano function, not when Theano is installed. But we cache this code generation/compilation.

This is why the first call can be much slower then the following one. This is "normal". We want to speed up the first call, but this is a goal that isn't moving fast recently.

So you did nothing wrong.

**Comment by kobecsb** [comment]
Oh, I'm sorry I didn't express myself clearly. From my observation, even if it's not the first time compiling, the speed is much slower than the previous version.

**Comment by nouiz** [comment]
I don't have an idea. If you want to investigate a little, you can enable
Theano profile while enabling Theano optimizer profile.

This will tell us where the time is spend. If we compare both, we could see
the difference.

In both case with with the extra flags profile=True and
profile_optimizer=True. Redirect the output to a file and send me both.

If you can only time the current version sending it would also help.
